### ISSUE TITLE
Colors bad

### ISSUE THREAD

**Issue by mizlan** [justsharan/periodic-table#2]
I don't think I am using any sort of style injection but this is what it looks like to me:

<img width="1645" alt="image" src="https://user-images.githubusercontent.com/44309097/120057656-aa4f0780-bff9-11eb-8046-06996b552b8e.png">

In my opinion, that contrast is bad. Could a better selection of colors be used instead?

**Comment by justsharan** [comment]
Which colors don't you like? (the background, the elements, etc)

**Comment by mizlan** [comment]
The black-on-dark makes it hard to read the element information.

**Comment by mizlan** [comment]
I would expect lighter background colors for the different elements.

**Comment by justsharan** [comment]
How about now?

**Comment by mizlan** [comment]
Sure, that's better, but it's still cutting it close. I appreciate the low-contrast aesthetic though. Closing as it is sufficiently legible for me.
